version: "3.8"

services:
  postgres:
    image: postgres:16.6-alpine
    container_name: test_postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      retries: 5
      start_period: 10s
    networks:
      - test_network

  backend:
    build: .
    container_name: test_api
    environment:
      DATABASE_URL: "postgresql://testuser:testpassword@postgres:5432/testdb?schema=public"
      APP_PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: >
      bash -c "
        pnpm run prisma:migrate deploy &&
        pnpm run dev
      "
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
