# fly.toml app configuration file generated for monchef-api-prod on 2025-01-22T08:38:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'monchef-api-prod'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
